services:
  - type: web
    name: laravel-ecommerce
    env: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      cp .env.render .env
      php artisan key:generate --ansi
      npm install
      npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: sqlite
      - key: LOG_CHANNEL
        value: errorlog